// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUi6MdvijX0-InkjWXEWJ79Vod9HJE-Ao',
    appId: '1:804617959712:android:be3e2c53ee56c43c87bf45',
    messagingSenderId: '804617959712',
    projectId: 'nutriscan-713de',
    storageBucket: 'nutriscan-713de.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVf9gwLqDHy4bxPXW0EJCpHE3GKGskMyM',
    appId: '1:804617959712:ios:df916f9f240792f387bf45',
    messagingSenderId: '804617959712',
    projectId: 'nutriscan-713de',
    storageBucket: 'nutriscan-713de.firebasestorage.app',
    androidClientId: '804617959712-1dsj96demjn90hc5tdtcujurate5irm7.apps.googleusercontent.com',
    iosClientId: '804617959712-vs7vk8ceucpgqbl0vsv1lra7n5tmutis.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutriscan',
  );
}
