import 'package:nutriscan/models/food.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfExportService {
  /// Generates a PDF report of logged food meals and shares/prints it
  static Future<void> exportNutritionReport(List<Food> foods) async {
    final pdf = pw.Document();

    final totalCalories = foods.fold(0.0, (sum, f) => sum + f.calories);
    final totalProtein = foods.fold(0.0, (sum, f) => sum + f.protein);
    final totalCarbs = foods.fold(0.0, (sum, f) => sum + f.carbs);
    final totalFat = foods.fold(0.0, (sum, f) => sum + f.fat);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // Document Title
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('NutriScan - Nutrition Log Report',
                      style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text(DateTime.now().toString().split(' ')[0],
                      style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey700)),
                ],
              ),
            ),
            pw.SizedBox(height: 16),

            // Macro Overview Container
            pw.Container(
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                color: PdfColors.teal50,
                borderRadius: pw.BorderRadius.circular(8),
                border: pw.Border.all(color: PdfColors.teal300),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                children: [
                  _buildPdfStat('Total Meals', '${foods.length}'),
                  _buildPdfStat('Calories', '${totalCalories.round()} kcal'),
                  _buildPdfStat('Protein', '${totalProtein.round()}g'),
                  _buildPdfStat('Carbs', '${totalCarbs.round()}g'),
                  _buildPdfStat('Fat', '${totalFat.round()}g'),
                ],
              ),
            ),
            pw.SizedBox(height: 24),

            pw.Text('Logged Meal History',
                style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 12),

            // Table of Foods
            pw.TableHelper.fromTextArray(
              headers: ['Food Name', 'Calories', 'Protein', 'Carbs', 'Fat', 'Health Score'],
              data: foods.map((f) {
                return [
                  f.name,
                  '${f.calories.round()} kcal',
                  '${f.protein.toStringAsFixed(1)}g',
                  '${f.carbs.toStringAsFixed(1)}g',
                  '${f.fat.toStringAsFixed(1)}g',
                  '${f.healthScore}/10',
                ];
              }).toList(),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.teal700),
              rowDecoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300))),
              cellAlignment: pw.Alignment.centerLeft,
              cellPadding: const pw.EdgeInsets.all(8),
            ),

            pw.SizedBox(height: 32),
            pw.Divider(),
            pw.Center(
              child: pw.Text('Generated by NutriScan AI Health App',
                  style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
            ),
          ];
        },
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: 'nutriscan_nutrition_report.pdf',
    );
  }

  static pw.Widget _buildPdfStat(String label, String value) {
    return pw.Column(
      children: [
        pw.Text(value, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.teal900)),
        pw.Text(label, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
      ],
    );
  }
}
